easy_admin:
  user:
    name_property_path: 'surname'
    display_name: true
  site_name: "Administration de la base de donnée CDLM"
    # List the entity class name you want to manage
  entities:
    Article:
      class: App\Entity\Article
      list:
        fields: ['id', 'title', 'date_event', 'format', 'created_at', { property: 'imgs.id', label: 'Image' }, { property: 'user.surname', label: 'Nom'}]
    Img:
      class: App\Entity\Img
    Users:
      class: App\Entity\Users
