easy_admin:
  design:
    templates:
      label_null: 'base.html.twig'
  user:
    name_property_path: 'surname'
    display_name: true
  site_name: "Administration de la base de donnée CDLM"
  # List the entity class name you want to manage
  entities:
    Article:
      class: App\Entity\Article
      image_base_path: '%picture_directory%'
      list:
        fields: 
          - 'id'
          - 'title'
          - 'date_event'
          - 'format'
          - 'created_at'
          - { property: 'imgs.name', label: 'Image', type: 'image' }
          - { property: 'user.surname', label: 'Nom' }
    Img:
      class: App\Entity\Img
      image_base_path: '%picture_directory%'
      list:
        fields:
          - 'id'
          - { property: 'name', label: 'Image', type: 'image'}
          - { property: 'uploaded_at', label: "Date d'upload"}
    Users:
      class: App\Entity\Users
      list:
        fields:
          - 'surname'
          - 'name'
          - 'mail'