easy_admin:
  design:
    templates:
      label_null: 'base.html.twig'
  user:
    name_property_path: 'surname'
    display_name: true
  site_name: "Administration de la base de donnée CDLM"

  # List the entity class name you want to manage
  entities:
    Article:
      class: App\Entity\Article
      form:
        fields:
          - { property: 'imgs.imgData', label: 'Images', type: 'file', base_path: '%app.path.images%' }  
      list:
        fields: 
          - 'id'
          - 'title'
          - 'date_event'
          - 'format'
          - 'created_at'
          - { property: 'imgs.name', label: 'Images', type: 'array', base_path: '%app.path.images%' }
          - { property: 'user.surname', label: 'Nom' }
    
    Img:
      class: App\Entity\Img
      list:
        fields:
          - { property: 'name', label: 'Image', type: 'image', base_path: '%app.path.images%'}
          - { property: 'uploaded_at', label: "Date d'upload"}
      form:
        fields:
          - { property: 'name', type: 'file', base_path: '%app.path.images%'}
    
    Users:
      class: App\Entity\Users
      list:
        fields:
          - 'surname'
          - 'name'
          - 'mail'
          - 'articles'
          - 'roles'