easy_admin:
  site_name: 'Administration de la base de données CDLM'
  
  list:
    actions: 
      - { name: 'show', icon: 'eye', label: false }
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'trash', label: false }
  
  design:
    templates:
      label_null: 'base.html.twig'
    menu:
      - { entity: 'Article', label: 'Articles', icon: 'newspaper' }
      - { entity: 'Img', label: 'Images', icon: 'images' } 
      - { entity: 'Users', label: 'Membres', icon: 'user' }

  user:
    name_property_path: 'surname'
    display_name: true

  # List the entity class name you want to manage
  entities:

    Article:
      class: App\Entity\Article
      show:
        fields: 
          - id
          - title
          - date_event
          - format
          - created_at
          - imgs
          - { property: 'user', label: 'Membre' }
      #form:
      #  form_options:
      #    data_class: null
      #    upload_dir: '%app.path.images%'
      #    download_dir: '%app.path.images%'
      #    multiple: true
      #  fields:
      #    - { property: 'imgs', type: 'file' }
      #    - { property: 'text', type: 'text_editor' }
      list:
        fields: 
          - id
          - title
          - date_event
          - format
          - created_at
          - imgs
          - { property: 'user', label: 'Membre' }
    
    Img:
      class: App\Entity\Img
      list:
        fields:
          - id
          - { property: 'name', label: 'Image', type: 'image', base_path: '%app.path.images%' }
          - { property: 'uploaded_at', label: "Date d'upload" }
          - { property: 'idArticles', label: "Articles" }
      form:
        fields:
          - { property: 'name', type: 'file', base_path: '%app.path.images%', multiple: true }
          - idArticles
      show:
        fields:
          - id
          - { property: 'name', label: 'Image', type: 'image', base_path: '%app.path.images%' }
          - { property: 'uploaded_at', label: "Date d'upload" }
          - { property: 'idArticles', label: "Articles" }
    
    Users:
      class: App\Entity\Users
      list:
        fields:
          - surname
          - name
          - { property: 'mail', label: 'Email', type: 'email' }
          - { property: 'articles', label: "Nombre d'articles" }
          - { property: 'roles', label: 'Accès' }
          - { property: 'last_log', label: 'Dernière connexion' }